//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colaboradores_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboradores
    {
        public int Id_Colab { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Email { get; set; }
        public string BI { get; set; }
        public string NIF { get; set; }
        public string Morada { get; set; }
        public string Concelho { get; set; }
        public string Distrito { get; set; }
        public Nullable<int> Departamento { get; set; }
    }
}
